---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overlay
rules:
- apiGroups: ["rbac.istio.io"]
  resources: ["servicerolebindings", "secret"]
  verbs: ["create", "get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: overlay
subjects:
- kind: ServiceAccount
  name: app
roleRef:
  kind: ClusterRole
  name: overlay
  apiGroup: rbac.authorization.k8s.io
