apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: "bind-ml-pipeline-nb-{{name}}"
  namespace: "{{name}}"
spec:
  roleRef:
    kind: ServiceRole
    name: ml-pipeline-services
  subjects:
  - properties:
      source.principal: "cluster.local/ns/{{name}}/sa/default-editor"
